// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGmftPQB56MMQefTtpKgooCr_2VpuYa3M',
    appId: '1:428425010887:web:47df32633c197a54bca8e2',
    messagingSenderId: '428425010887',
    projectId: 'aidkriya-app-c9520',
    authDomain: 'aidkriya-app-c9520.firebaseapp.com',
    storageBucket: 'aidkriya-app-c9520.firebasestorage.app',
    measurementId: 'G-GBV8SD3KXL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW1ACgq0o0Me9PmTFgqRDgz18Nzfrni9s',
    appId: '1:428425010887:android:6602c242e4b88893bca8e2',
    messagingSenderId: '428425010887',
    projectId: 'aidkriya-app-c9520',
    storageBucket: 'aidkriya-app-c9520.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5RNip2ai54-yPi5hlGkIZ2w4-OoT6pbU',
    appId: '1:428425010887:ios:480f4d0377f03090bca8e2',
    messagingSenderId: '428425010887',
    projectId: 'aidkriya-app-c9520',
    storageBucket: 'aidkriya-app-c9520.firebasestorage.app',
    iosBundleId: 'com.example.aidkriyaWalker',
  );
}
